spring:
  application:
    name: SpringBootBasic
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: edu
    password: edu12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      enable_lazy_load_no_trans: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
   uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false
    path: /error

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml